### ISSUE TITLE
Camera stays indefinitely on

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#2149] opened 2022-04-29 09:14 UTC
In some special circumstances, the camera LED can stay indefinitely on (even when we close the camera)

To reproduce:

- Enable your camera
- Move your Woka next to a silent zone (about 1 tile away)
- Wait for your camera to turn off automatically
- Now, move towards the silent zone. The animation of your webcam window at the bottom right must just have the time to start.
- If timed properly, the webcam LED will turn on and stay on inside the silent zone

After that, it will never be turned off again

**Comment by moufmouf** [comment] 2022-04-29 09:53
This might be related to a race condition here:

http://github.com/thecodingmachine/workadventure/blob/d6450831c6aca33996089e9302fd015e12a7b1f3/front/src/Stores/MediaStore.ts#L431-L431

Possible scenario:

- we receive a constraint to enable the camera
- we request the camera to the browser (and wait for response)
- before the browser is sending a response, we receive another constraint to shutdown camera
- then the promise to activate the camera finishes?

**Comment by buenni86** [comment] 2022-05-03 08:01
It is the same if you try to change your microphone through the camera settings.

**Comment by cesar-cardinale** [comment] 2022-05-03 14:37
It seems to be fixed on the last version in the develop branch.
I can't reproduce this bug in this version.

**Comment by ValdoTR** [comment] 2022-05-06 08:27
It seems that when you switch fast between cam OFF and ON (or ON and OFF) the hardware is not able to detect it.
So for example, go into the start zone in the village (silent), your LED if OFF:
![image](https://user-images.githubusercontent.com/14997703/167095487-3f1065c6-e32d-4ff6-822c-1dd4d1bf7492.png)
And walk into the "Register" zone. The LED is ON even if you are in a silent zone because you walked into a non silent zone just before.

**Closed** 2022-05-10 10:01 UTC
Labels: bug
