### ISSUE TITLE
Behind a Corporate Proxy Server

### ISSUE THREAD

**Issue by buenni86** [thecodingmachine/workadventure#621] opened 2021-01-19 09:36 UTC
I have setup docker and docker-compose to use the proxy, but I think the images are not using them correctly.

**Comment by buenni86** [comment] 2021-01-19 12:27
Found something which is possibly the cause.
wget needs an update, the version in the containers is unable to handle https proxy.

https://gitlab.alpinelinux.org/alpine/aports/-/issues/10446

**Comment by klepptor** [comment] 2021-01-21 09:30
I'm having the same issue here. Did you already try to update the wget version in the containers manually during runtime as described in your link? When the problem is solved after that it should be easy to do a PR to this!?

**Comment by buenni86** [comment] 2021-01-21 10:37
Updating is impossible, since without a working proxy no internet access.
I downloaded wget on the host and did copy it into the container and started the download.
It was successful, but i don't know how i can tell docker-compose to copy my local wget file into the container on startup.
I think the developers have to update their containers with full wget instead of the busybox wget version.

**Comment by moufmouf** [comment] 2021-01-22 08:55
Hey guys,

The issue is not `wget`. The problem arises because at startup, yarn is trying to install dependencies.
It is doing so because the docker-compose.yaml file is targetted at a development environement.

If you are trying to do a production deployment, you should instead use the Docker images available on Docker Hub.
They have all the dependencies already downloaded so they won't try to do outbound network accesses.

We still need to properly document how to do a proper stand-alone production setup!

**Comment by klepptor** [comment] 2021-01-22 09:57
Grr, I lost several hours on trying to get a working wordadventure. ;)

Do you have a working docker-compose.yaml for production? That would be great as there isn't just a simple switch to change between develop and prod in the Yaml or the .env file. I don't get it to work at all by just using the prod images.

E.g. what's the equivalent for the messages service image thecodingmachine/nodejs:14? And the environment vars have to be adjusted too, right?

**Comment by klepptor** [comment] 2021-02-01 12:35
Any news on this? @moufmouf Sorry for still asking, but we would love to use Workadventure in our LAN, but can't! ;)

**Comment by gounthar** [comment] 2021-02-11 20:53
Same in here!

**Comment by gparant** [comment] 2021-04-24 14:09
We have deployed docker compose for production #698 

I close this issue and we still available if you have any other question.
Thansk for your feedback 💪

**Closed by gparant** 2021-04-24 14:09 UTC
