### ISSUE TITLE
Issues with new Co-Website features

### ISSUE THREAD

**Issue by Lurkars** [thecodingmachine/workadventure#1791] opened 2022-01-28 18:24 UTC
I must complain, that I don't understand this change in removing the websiteTriggerMessage completely in #1620. First of all, I just liked the feature as it was, also it's in line with jitsi triggers etc. But what is biggest case for me is, that I removed the Icon feature for Co-Website due to privacy reasons. But with this, I need to add a generic icon which then gives no context at all about the website to open. Also there may be sites offering generic/not easy relatable icons, so even with icon I have no hint about what will be opened on click. So first question, is there any chance in putting back the triggerMessages? And if not, I really would appreciate an explanation about the decision about removing this. @nolway @moufmouf

**Comment by moufmouf** [comment] 2022-01-28 20:35
Hey @Lurkars ,

Here is the big picture:

We want a system where we can have many websites loaded at once (with the ability to maximize/minimize websites when there are several loaded). Think about this:

A meeting room with:

- Jitsi
- A whiteboard or mural
- A Google Doc
- A Google sheet
- etc...

In the near future, we will add the ability for anyone to share links too. So we needed some kind of "taskbar" where the sites could be stored.

Now, I agree we should probably find a way to display the "websiteTriggerMessage" too. We have some ideas to improve this in the future.

A question though:

I don't understand the "privacy reasons". You don't want the IP of the user to be sent to the webserver that hosts the icon itself? Is that it? If so, you could maybe wrap an HTTP cache like Varnish around the icon server? That could solve your privacy issue?

**Comment by Lurkars** [comment] 2022-01-29 07:36
Is it possible that the icon stuff has changed? I didn't take a look now how the matthiasluedtke/iconserver works and if it is privacy friendly. But before the icons was fetched via Google if I remember correctly and at that point I just removed the code from co-website.

So I understand your vision. I am personally a bit sceptical, because it's also sounds a bit like WA becoming a browser with tab management, but in the end it is not much different from having multiple triggerMessage stacked and I agree that this is also not ideal. Still I am unsure about this and still think it will be good to keep the trigger message somehow to give user information about what to open. (I have for example in start area a trigger with like "First time here? Click to open tutorial..." and a link to our wiki. With current state there will just be a small favicon and new users will not get any hint that they should click it. And that's bad UX I think.) And this of course still stays that only icons wouldn't give enough context in many cases.

I also noticed that we start coming more in the discussion about what WA is for. Because I use it completely as a social tool in private context and of course this differs from the virtual office use case. So of course I am happy if we get the best for both worlds. (For specific "gaming" use case, I would also like to open multiple jitsi rooms at once, which is not possible. I have a workaround for this in by keep the P2P chat open. I may open another issue about this.)

**Comment by Lurkars** [comment] 2022-01-31 15:06
BTW: I had a PR #902 about this a long time ago: That the triggers reopen when close. In the end this is now the same function, but just removed the triggerMessage. It was a tough call for me, to re-implement this feature for myself to the new Co-Website API and it is now completely broken again. 

So I think a much better solution would be to have the **trigger message as they were before and create like a tray icon** (like the icon now, but maybe a bit smaller) **on close**, where the trigger get's put to after close. If we have this also for Jitsi we will get the best for both. **We have the triggers back, but also the "minimize" function.** (And I also get my feature, that after closing Website/Jitsi you need to walk in and out again to reopen!)

**Comment by pizkaz** [comment] 2022-02-02 09:06
I agree with @Lurkars. `openWebsiteTriggerMessage` is a widely used feature. Removing it - especially without offering a viable alternative - is a big regression IMHO. There are a many people in the XCE community asking me to *not* rebase to the current `develop` state because of this.

**Comment by sknebel** [comment] 2022-02-02 18:19
I have to agree: While I'm curious to see what the new solution looks like, at least until it's fully there and everybody had time to update their maps I'd very much prefer to have it working as is. For maps targeting the general public (i.e. not users that are familiar with a specific map) this is IMHO quite important to give context what to expect.

**Comment by moufmouf** [comment] 2022-02-04 16:23
Hey guys,

We have read your comments and it seems we need to think this through a bit more before tagging the next release.
Please note by the way that the latest tagged release does not have this feature yet.

Here is what we could do:

```
openWebsiteTrigger: onaction
openWebsiteTriggerMessage: some text
```

The properties above should behave is previously (open a clickable action message).


```
openWebsiteTrigger: onicon
```

With the property above, the website is minified in an icon in the taskbar.
We will remove the newly added `openWebsiteLazy` property since it is replaced by "onicon".

@Lurkars @pizkaz @jstsmthrgk @sknebel What do you think about this? Any better naming idea?

> I also noticed that the OPEN_WEBSITE_WIDTH was completely removed.

Thanks for the feedback, we'll look into this too.

**Comment by Lurkars** [comment] 2022-02-04 18:15
First of all, thanks for the feedback and it sounds like a better idea then the state now. Nevertheless, as I proposed later, I like the combination of both features, so that a website opened with a triggerMessage gets "minimized" to the taskbar after close. Maybe you can just add it anyway like you sad, so "onicon" trigger that puts Webpage directly to taskbar, but additionally "onaction" puts to taskbar after close. Because the problem before for me was, that if you close website or jitsi you have to walk in/out again for reopen. The taskbar perfectly solves this problems without spamming the screen with triggerMessages, so from my pov fits perfectly.

**Comment by pizkaz** [comment] 2022-02-04 22:24
I really like the approach @Lurkars describes. This way, we would get the best of both "worlds".

Also I would really like to see a setting, which allows users to completely disable cowebsites and Jitsis (or any connection to a third-party site, really) as implemented in #1691. I'd be willing to help implementing that. :-)

**Comment by Lurkars** [comment] 2022-02-07 18:56
Looks good in first place. I just experience issue, that if site is loading and I walk out of layer, website is still open and stays! So this is bug and need to be fixed. Also i18n message is missing (PR from me was already merge before changing Co-Website stuff). Besides I just make a quick test and will report more when I tested more! But also nice for Jitsi!

**Comment by moufmouf** [comment] 2022-02-08 08:25
> I just experience issue, that if site is loading and I walk out of layer, website is still open and stays! So this is bug and need to be fixed. 

Geez! Again this bug!
@nolway could a cancelable promise be useful here?

**Comment by Lurkars** [comment] 2022-02-10 12:44
I just tested #1838 ! Mentioned issue seems to be fixed for me. @nolway @moufmouf  I still just have some additions:
- I would like to have the triggerMessage shown on hover over website icon, so one can better see which sites are minimized, (this lead to next point)
- from a technical perspective the triggerMessage should be attached to the CoWebsite object (so I can build previous point myself, if not it's not liked)
- the main site should have a different border color or something, at least some hint, which site is where
- when clicking on the icon of the main page, I expect the page to close and put the other page to main (instead of just switching)
- the icon sizes of the main site changes when opening/closing second site
- really personal wish: possibility to handle Jitsi completely same as Co-Website (so multiple Jitis can be opened etc)

**Comment by Lurkars** [comment] 2022-02-10 13:00
Another bug I noticed: when I click close icon of Jitis and then click on the Icon to reopen, I just get coffee mug logo (loading indicator). So Jitis does not reopen.

**Comment by nolway** [comment] 2022-02-10 18:55
> Another bug I noticed: when I click close icon of Jitsi and then click on the Icon to reopen, I just get coffee mug logo (loading indicator). So Jitsi does not reopen.

The fix has been available on the develop branch ;)

> I would like to have the triggerMessage shown on hover over website icon, so one can better see which sites are minimized, (this lead to next point)

We think that was not a good idea because this message is displayed in the action message triggered by a press on the space bar (Press SPACE to ...), on the icon context the message will be partially false.

> the main site should have a different border color or something, at least some hint, which site is where
> when clicking on the icon of the main page, I expect the page to close and put the other page to main (instead of just switching)

Done in #1852 

> the icon sizes of the main site changes when opening/closing second site

Are you sure about that ? Normally the size of icon is set on the same size, did you have a process to reproduce this ?

> really personal wish: possibility to handle Jitsi completely same as Co-Website (so multiple Jitis can be opened etc)
Now it's possible but we close all jitsi when you got outside of the tiles because we can't identify witch cowebsite we must close.

**Comment by Lurkars** [comment] 2022-02-11 13:46
> > Another bug I noticed: when I click close icon of Jitsi and then click on the Icon to reopen, I just get coffee mug logo (loading indicator). So Jitsi does not reopen.
> 
> The fix has been available on the develop branch ;)

Yes already noticed, thanks.

> 
> > I would like to have the triggerMessage shown on hover over website icon, so one can better see which sites are minimized, (this lead to next point)
> 
> We think that was not a good idea because this message is displayed in the action message triggered by a press on the space bar (Press SPACE to ...), on the icon context the message will be partially false.

Yes totally understand this, that's why I asked to put the text into Co-Website, so I can more easily change this myself. But I can also do it completely myself, will be just more difficult to maintain.

> > the main site should have a different border color or something, at least some hint, which site is where
> > when clicking on the icon of the main page, I expect the page to close and put the other page to main (instead of just switching)
> 
> Done in #1852

Nice, looking forward to check it.

> > the icon sizes of the main site changes when opening/closing second site
> 
> Are you sure about that ? Normally the size of icon is set on the same size, did you have a process to reproduce this ?

I think I didn't write exactly what I meant, because I didn't explicit mentioned the action icons like close, fc, swap, so maybe this was not clear.

I attached screenshots, Browser used Firefox 96.0, Ubuntu 21.04, Private Session

![co-website-opened](https://user-images.githubusercontent.com/2760570/153601876-07334a2c-033a-4807-a400-f953348dfb64.png)
![co-website-closed](https://user-images.githubusercontent.com/2760570/153601884-2bbcb540-c3f7-429d-a80c-129caa2a9618.png)

> > really personal wish: possibility to handle Jitsi completely same as Co-Website (so multiple Jitis can be opened etc)
> 
> Now it's possible but we close all jitsi when you got outside of the tiles because we can't identify witch cowebsite we must close.

Okay, I will test this again.

**Comment by Lurkars** [comment] 2022-02-12 14:02
@nolway forget about the size issues. Seems to be due to some local changes. I don't have the issue in vanilla.

**Comment by Lurkars** [comment] 2022-02-13 20:02
I still found some bugs, but for better overview I will open separate issues, because this was more about the function in general!

**Closed** 2022-02-13 20:02 UTC
