### ISSUE TITLE
Large Tilesets (>4094px) not loading -> Black Elementes

### ISSUE THREAD

**Issue by sitzer** [thecodingmachine/workadventure#749] opened 2021-02-16 10:17 UTC
Was discovered during #rc3 preparations: If you use Tilesets larger than 4094px these won't get loaded in some Browsers. You'll only get black tiles. The Workaround is to split up the tiles ins smaller snippets.  
![largeTilesets](https://user-images.githubusercontent.com/4426016/108048457-58383680-7047-11eb-8360-5055e70f8525.png)
I though this is a known bug, but couldn't find it in the isssues. As @gparant is using the 14368px high modern_interiors.png in  https://github.com/gparant/tcm-client/tree/master/TCM/start-up I thought I tell you ;)

**Comment by moufmouf** [comment] 2021-02-18 16:37
Thanks @sitzer !
I was suspecting something like this but I was not aware the limit was 4096px.
We can certainly improve the code a bit by adding an easy to read error in the console when we encounter such a large file.

**Comment by mploigt** [comment] 2021-02-26 13:03
It would be great if it would also just work with larger tiles :) Is there no other way to split the large tile into two and re-layout everything in this map?

**Comment by kno10** [comment] 2021-03-13 15:23
2kx2k and 4kx4k are common texture size limits in GL drivers.
So it may not only depend on the browser, but also whether the renderer uses GL or not.

**Comment by tabascoeye** [comment] 2021-03-15 12:12
Indeed the problem is gone with ````?phaserMode=canvas```` appended to the URL

**Comment by dassmilytier** [comment] 2021-03-25 10:33
Thanks for the workaround. Was stuck for a while until I came across this issue ticket. Clipping the tileset wasn't an option for me.

- Only thing left would be that the url parameter will not be removed during game loading. This way when sharing the url I realized that all people had the block tile problem.

- Even better alternative would be to allow parameters like this within the json file, so users wont be bothered with parameters.

**Comment by moufmouf** [comment] 2021-03-25 17:51
I'm actually thinking about writing a "map optimizer" program that would regenerate a PNG file from the only tiles on a map that are actually used. This way, the textures would automatically be reduced to <4096px most of the time.

I'm lacking proper time to do this but I hope I'll be able to achieve this some day.

**Comment by tabascoeye** [comment] 2021-03-25 18:47
Considering animations, this will be more complicated to code than you might think...

**Comment by khjoanna** [comment] 2021-04-15 15:47
Hey I have the same issue, but my tilesets are not so large. So my tiles were loading without any problem, then I started adding more tile layers and other tiles suddenly not anymore even my avatar on workadventure doesn't appear anymore. Do you maybe have any idea what the problem could be? (I am no programmer)

**Comment by moufmouf** [comment] 2021-04-15 16:07
Hi @khjoanna ,
Interesting. I have no idea where your problem could come from? Is this happening in Firefox only?
Could you share the map with us (if it is public) so we can have a look at the issue?

**Comment by khjoanna** [comment] 2021-04-15 16:11
Hey thanks for getting back. Yes sure I can share, maybe I am not seeing something very obvious. No I tried both with Firefox and Safari, absolutely the same. Here the links, I tried resaving the same map, to see if it would make a difference, but nothing. So here you go:
https://github.com/khjoanna/PRESENTATION/blob/main/BLA_1.json
https://github.com/khjoanna/PRESENTATION/blob/main/BLA_2.json

**Comment by tabascoeye** [comment] 2021-04-15 17:21
Does adding `?phaserMode=canvas` to the end of your URL help?

**Comment by khjoanna** [comment] 2021-04-15 18:24
Yes I tried, same result. :(

> Does adding `?phaserMode=canvas` to the end of your URL help?

**Comment by khjoanna** [comment] 2021-04-15 18:25
It may be relevant that I use PNG files created by me on a drawing board.

**Comment by tabascoeye** [comment] 2021-04-15 19:08
then it is a different bug than the one in this issue (WebGL related).

**Comment by SimonGalet** [comment] 2022-02-01 11:07
Hi @moufmouf,

I love your idea about a "map optimizer", did you have time to work on that ?
We worked on tiled with a tilesheet too big, and we realized that too late so we have to remake everything if we want our tiles to appear.

It works with `?phaserMode=canvas` but I have a feeling that it's not running as smoothly as WebGL.
Is canvas renderer less performant than WebGL ?

Thank you a lot !

**Comment by tabascoeye** [comment] 2022-02-01 13:04
Yes it is. That's why WebGL is the default when supported by device and browser.
If you already use a too large tileset you might be out of luck and need to cut it in more smaller ones and redo some of your work.
I don't believe there is a tiled plugin for that

**Comment by kaeff** [comment] 2022-08-18 21:00
Hi folks, I ran into the same issue. My map also uses the large modern_interiors.png. . I solved it by using the wa-map-optimizer. Sharing the steps in case others find it useful. 

The map optimizer that @moufmouf suggested was built in the meanwhile: https://github.com/nolway/wa-map-optimizer-vite. The latest starter kit (v3.1.3) uses it: https://github.com/thecodingmachine/workadventure-map-starter-kit.

This optimizer generates new tileset pngs containing only required tiles, and updates the map json accordingly.

It's a vite plugin so if you are using webpack (used in older versions of the starter-kit), you can upgrade to vite like so:
1. Copy the package.json and vite.config.ts from the map-starter-kit and delete the webpack config files.
2. In the map files, change the map's `script` property: Instead of `script.js` (previous bundle built by webpack), reference the actual main source file (e.g. `src/main.ts`)
3. Update the build pipeline (e.g. github actions) to deploy the output of the `dist/` folder

**Comment by moufmouf** [comment] 2022-08-19 10:09
Thanks @kaeff for updating this issue :heart:

I guess we can finally close it :+1:

**Closed by moufmouf** 2022-08-19 10:09 UTC
