### ISSUE TITLE
request for doku: how to use openid ?

### ISSUE THREAD

**Issue by ka7** [thecodingmachine/workadventure#1491] opened 2021-09-28 17:11 UTC
Hi,

I see that latest release support somehow openid, and from what i find in code you did some tests using [hydra](https://www.ory.sh/hydra/).
Also can ready, otheres e.g. keykloac wont work out of box (because using incompatible type of openid)

Can you provide some simple howto ?

Assuming, I can connect (in parallel to anonymous users) as authenticated - what are the benefits ?
Re-using same auth for Jitsi-integration (and being then there an room-admin with same-name in addition to anonymous users) is something I understand.

Sorry, quite new to openid, workadventure ...

.ka

**Comment by Lurkars** [comment] 2021-09-29 04:33
The main problem for now is in https://github.com/thecodingmachine/workadventure/blob/develop/front/src/Connexion/ConnectionManager.ts where OIDC relies on `this._currentRoom.iframeAuthentication` which can only be set on an Admin API provided instance.

If you feel free to adopt code, you can skip the if-clause and directly use this redirect URL code
```
const redirectUrl = `${PUSHER_URL}/login-screen?state=${state}&nonce=${nonce}&playUri=${this._currentRoom.key}`;
        window.location.assign(redirectUrl);
        return redirectUrl;
```
Nevertheless you're right that the use of OIDC is quite useless with anonymous login enabled and no Admin API. I personal have an instance with anonymous disabled and a custom admin API. My changes are therefore in conflict with current use cases, that's why I didn't push those changes. But you're welcome to gain more help if needed.

**Comment by Lurkars** [comment] 2021-11-26 13:27
This has been merged, so usage of OpenID in self hosted environment is now making sense. I think documentation is lacking, but I may write down a quick guide. It's only a setup of some env variables and explaining what they do. So basically we're back to the original topic here: lack of documentation.

**Comment by Lurkars** [comment] 2021-11-27 06:09
@gparant wrote something here
@1533#issuecomment-980040580 
In the end only the env properties listed on the end are important for usage.

**Comment by ateuber** [comment] 2022-02-09 14:25
Thank you! I got this working with our provider by adding `id_token_signed_response_alg: "PS256",` after this line: https://github.com/thecodingmachine/workadventure/blob/c39f23de6fa4b4f0705f0afa51cc2acd586562c1/pusher/src/Services/OpenIDClient.ts#L19 

I think a setting for this response algorithm would be helpful.

**Comment by fcecagno** [comment] 2022-02-16 02:59
Hi guys, trying to use opid login with Google. The login part worked, however it looks like the user information retrieval does not - users log in but have to fill manually full name and the profile isn't accessible.
On the pusher logs, I see this:
```
openIDCallback => fetchMemberDataByUuid Error: No admin backoffice set!
at AdminApi.fetchMemberDataByUuid (/usr/src/dist/src/Services/AdminApi.js:32:35)
at AuthenticateController.getUserByUserIdentifier (/usr/src/dist/src/Controller/AuthenticateController.js:260:46)
at /usr/src/dist/src/Controller/AuthenticateController.js:58:56 
```
We're using `OPID_PROFILE_SCREEN_PROVIDER=https://www.googleapis.com/oauth2/userinfo.profile`. Any insight on this? Thanks!

**Comment by Lurkars** [comment] 2022-02-16 07:18
The email address is the only user data used as ID by now. So this is all currently "works as designed". There is no usage of other profile data, even if it is fetched correctly. So username for example must be set manually. I personally have changes to use username and locale, I may help you using it.

**Comment by fcecagno** [comment] 2022-02-16 12:07
Nice work, thanks @Lurkars . How do I confirm the ID is being set properly? We'll test #1881 as well.

**Comment by Lurkars** [comment] 2022-02-16 12:24
> Nice work, thanks @Lurkars . How do I confirm the ID is being set properly? We'll test #1881 as well.

If you take a look at localStorage, there should be `localUser` object with `uuid` set to your OIDC email address or subject.

**Comment by fcecagno** [comment] 2022-02-18 01:41
Hi @Lurkars , we confirmed `OPID_PROFILE_SCREEN_PROVIDER` isn't needed in order to have `localUser` properly set with the e-mail address on local storage.

**Comment by Lurkars** [comment] 2022-03-01 05:21
#1881 has been merged with via #1934.

**Comment by pizkaz** [comment] 2022-03-28 18:58
> The email address is the only user data used as ID by now. So this is all currently "works as designed". There is no usage of other profile data, even if it is fetched correctly. So username for example must be set manually. I personally have changes to use username and locale, I may help you using it. (EDIT: I created PR for this)

I have successfully set up OIDC login via Keycloak but even with #1881 merged I still have to manually enter my user name.
Could you point me in the right direction how to set this up? I'm guessing I have to somehow tell Keycloak to transmit the `username` and `locale` claims, right?

**Comment by Lurkars** [comment] 2022-03-28 19:25
I am not familiar with keycloak setup, but yes, provider must of course deliver those data in ID token. I would think that you would be able to define claims/scopes in keycloak to be send. With `OPID_SCOPE` `OPID_USERNAME_CLAIM` and `OPID_LOCALE_CLAIM` you should also be able to change the claims used to your needs. Maybe keycloak uses username in the `sub` claim, then just set this.

**Comment by pizkaz** [comment] 2022-03-28 20:29
Got it: Default username claim provided by Keycloak is `preferred_username`, so one has to set

```
OPID_USERNAME_CLAIM=preferred_username
```

in `.env`.

**Comment by fcecagno** [comment] 2022-04-01 00:42
Just wanted to add that, in order to do the same as @pizkaz with Google, you'll need to set:
```
OPID_USERNAME_CLAIM=given_name
OPID_SCOPE=openid email profile
```
Default value for `OPID_SCOPE` is `openid email`, however `profile` is required to get the user name. More on https://developers.google.com/identity/protocols/oauth2/openid-connect#an-id-tokens-payload

**Comment by pizkaz** [comment] 2022-04-26 08:13
Is it possible to give users the admin tag with OIDC? Has anyone tried this? :-)

**Closed** 2022-08-09 16:20 UTC

**Comment by taksan** [comment] 2022-10-26 23:48
I know this has been closed, but if anyone ends up here, this is the expected value for OPID_PROFILE_SCREEN_PROVIDER:

OPID_PROFILE_SCREEN_PROVIDER=https://www.googleapis.com/auth/userinfo.profile

I just found out
