### ISSUE TITLE
Connecting 2(+1) maps with more than 1 start/exit layer is strange.

### ISSUE THREAD

**Issue by cbluoss** [thecodingmachine/workadventure#422] opened 2020-11-15 20:58 UTC
What we expected: Connect 2 maps with as many start/exit combinations as you like should work just as well as a single start/exit connection.

What we got: Completly unpredictable behaviour which startLayers will be used if entering another map.
Even other maps with just a single link are effected.

**Comment by moufmouf** [comment] 2020-11-16 08:00
Weird...

Could you point me to your map file so I can have a look at it?

**Comment by cbluoss** [comment] 2020-11-16 08:16
We 'fixed' it by splitting one of the maps, but I try to  create a example map.

**Comment by cbluoss** [comment] 2020-11-16 09:13
Okay, I build you a demo map, which was actually harder than I thought to be.

https://play.workadventu.re/_/global/cbluoss.github.io/wa-bugy-portals/map.json
Its usually fine after initial loading the map and it starts after several walks through the portals.

Note: This demo map was completly normal before I added room 3.

**Comment by psy** [comment] 2020-11-19 10:47
From what I understood this problem is caused by the game scenes (maps) preloaded and stored with their url (without the hash) as key. If you define multiple exits to the same map with different entry points, only the first will be stored and all others wont be considered as they have the same key. 

Should be fixed by https://github.com/thecodingmachine/workadventure/pull/435

**Closed** 2020-11-22 12:20 UTC
