### ISSUE TITLE
Screen sharing glitch

### ISSUE THREAD

**Issue by ValdoTR** [thecodingmachine/workadventure#282] opened 2020-09-20 14:59 UTC
https://www.loom.com/share/e9e3106988e44db0b23b3d0ab6dcf192

**Comment by jacquesbh** [comment] 2020-10-02 22:04
I can confirm this behavior.

**Comment by moufmouf** [comment] 2020-10-05 07:37
I see.
You are walking next to a Jitsi Meet zone and it is opening and closing very fast (because you walk on the zone only a few milliseconds)...

Maybe we should display the iframe only after 1 second (or on "onLoad") and display a small loader meanwhile?

**Closed** 2020-11-22 12:16 UTC
