### ISSUE TITLE
Can not draw popups in Tiled on a different object layer than "floorLayer"

### ISSUE THREAD

**Issue by ValdoTR** [thecodingmachine/workadventure#1236] opened 2021-06-25 15:22 UTC
Currently if we want integrate a popup by drawing a rectangle on an object layer, it is only taken by account if the we use the default "floorLayer".
It would be great to be able to draw our objects on a custom object layer in Tiled and use them in the script.

**Comment by jonnytest1** [comment] 2021-06-25 16:23
🤔 why do you need them in a different layer ?

**Comment by ValdoTR** [comment] 2021-06-28 10:44
I don't necessarily "need" to draw them in a different layer, but this is just for letting people as free as possible.
If these sorts of objects MUST be drawn in "floorLayer" then it must be specified in the doc, and this is not the case, that's why I opened this issue :)

**Comment by tabascoeye** [comment] 2021-07-09 09:44
duplicate of #929

**Comment by ValdoTR** [comment] 2021-12-13 11:48
Closing this as it is a duplicate (thanks @tabascoeye)

**Closed** 2021-12-13 11:47 UTC
